version: "3.4"

services:
  h2o-transcribe:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=base
    ports:
      - 9000:9000
    volumes:
      - ./app:/app/app
      - cache-pip:/root/.cache/pip
      - cache-poetry:/root/.cache/poetry
      - cache-whisper:/root/.cache/whisper
      - cache-faster-whisper:/root/.cache/faster_whisper

volumes:
  cache-pip:
  cache-poetry:
  cache-whisper:
  cache-faster-whisper:
